### ISSUE TITLE
Can not prgram the F1, F2 ---F6 keys

### ISSUE THREAD

**Issue by oalfarisi** [Baton34/Delux-T9-keyboard-key-remap-skin#1]
Hi, 
great work, the installation and the skin is successfully changes on the screen display, however i could not modify the Keys F1...F6 keys.
My keyboard Deluxe T9

![WIN_20210329_14_39_42_Pro (2)](https://user-images.githubusercontent.com/44928111/112825459-cfc4a100-909c-11eb-8636-f1f4ceace27b.jpg)

**Comment by Baton34** [comment]
Its work fine.
Choose F1 key, enter 'Z' for example, Click OK, click OK. And now when I press F1 on T9 keyboard it types 'Z'.
Can you are modify F.. keys with standard skin?
